package io.wyrmise.sunshine;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.TextView;

import java.util.ArrayList;

/**
 * Created by Demise on 6/8/2015.
 */
public class WeatherAdapter extends ArrayAdapter<Weather> {

    Holder holder;

    private ArrayList<Weather> weather;
    private Context context;

    public WeatherAdapter(Context c, int txtViewResourceID, ArrayList<Weather> arr) {
        super(c,txtViewResourceID);
        weather = arr;
        context = c;
    }

    /**
     * @effect get the View generated by the current instance of MessageAdapter
     */
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        View convertView1 = convertView;

        LayoutInflater vi = (LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);

        if(convertView1==null) {
            holder = new Holder();
            convertView1 = vi.inflate(R.layout.list_item, parent, false);
            holder.date = (TextView) convertView1.findViewById(R.id.date);
            holder.description = (TextView) convertView1.findViewById(R.id.description);
            holder.temperature = (TextView) convertView1.findViewById(R.id.temperature);
            holder.image = (ImageView) convertView1.findViewById(R.id.img);
            convertView1.setTag(holder);
        } else {
            holder = (Holder) convertView1.getTag();
        }

        Weather weather = getItem(position);

        holder.date.setText(weather.getDate());
        holder.description.setText(weather.getDescription().toUpperCase());
        holder.temperature.setText(weather.getMinTemp()+ (char) 0x00B0 + " - " + weather.getMaxTemp()+ (char) 0x00B0);

        String image = getImage(weather.getIcon());

        if(image!=null) {
            int resourceId = context.getResources().getIdentifier(
                    image, "drawable", context.getPackageName());
            holder.image.setImageResource(resourceId);
        }

        return convertView1;
    }

    private String getImage(String name){
        String image = null;

        switch (name){
            case "01d":
                image = "sunny";
                break;
            case "01n":
                image = "moon";
                break;
            case "02d":
                image = "cloudy_day";
                break;
            case "02n":
                image = "cloudy_night";
                break;
            case "03d":
                image = "broken_cloud";
                break;
            case "03n":
                image = "broken_cloud";
                break;
            case "04d":
                image = "scattered_cloud";
                break;
            case "04n":
                image = "scattered_cloud";
                break;
            case "09d":
                image = "shower_rain";
                break;
            case "09n":
                image = "shower_rain";
                break;
            case "10d":
                image = "rain";
                break;
            case "10n":
                image = "rain";
                break;
            case "11d":
                image = "thunderstorm";
                break;
            case "11n":
                image = "thunderstorm";
                break;
            case "13d":
                image = "snow";
                break;
            case "13n":
                image = "snow";
                break;
            case "50d":
                image = "fog_day";
                break;
            case "50n":
                image = "fog_night";
                break;
        }
        return image;
    }

    @Override
    public int getCount() {
        return weather.size();
    }

    @Override
    public Weather getItem(int position) {
        return weather.get(position);
    }

    private class Holder {
        public TextView description;
        public TextView date;
        public TextView temperature;
        public ImageView image;
    }
}
